import sqlalchemy
import sqlalchemy.orm


class SQLAlchemy:
    ##############################
    ### Sqlalchemy Sub Classes ###
    ##############################
    class ARRAY(sqlalchemy.ARRAY):
        ...

    class AdaptedConnection(sqlalchemy.AdaptedConnection):
        ...

    class Alias(sqlalchemy.Alias):
        ...

    class AliasedReturnsRows(sqlalchemy.AliasedReturnsRows):
        ...

    class AssertionPool(sqlalchemy.AssertionPool):
        ...

    class AsyncAdaptedQueuePool(sqlalchemy.AsyncAdaptedQueuePool):
        ...

    class BIGINT(sqlalchemy.BIGINT):
        ...

    class BINARY(sqlalchemy.BINARY):
        ...

    class BLOB(sqlalchemy.BLOB):
        ...

    class BOOLEAN(sqlalchemy.BOOLEAN):
        ...

    class BaseDDLElement(sqlalchemy.BaseDDLElement):
        ...

    class BaseRow(sqlalchemy.BaseRow):
        ...

    class BigInteger(sqlalchemy.BigInteger):
        ...

    class BinaryExpression(sqlalchemy.BinaryExpression):
        ...

    class BindParameter(sqlalchemy.BindParameter):
        ...

    class BindTyping(sqlalchemy.BindTyping):
        ...

    class Boolean(sqlalchemy.Boolean):
        ...

    class BooleanClauseList(sqlalchemy.BooleanClauseList):
        ...

    class CHAR(sqlalchemy.CHAR):
        ...

    class CLOB(sqlalchemy.CLOB):
        ...

    class CTE(sqlalchemy.CTE):
        ...

    class CacheKey(sqlalchemy.CacheKey):
        ...

    class Case(sqlalchemy.Case):
        ...

    class Cast(sqlalchemy.Cast):
        ...

    class CheckConstraint(sqlalchemy.CheckConstraint):
        ...

    class ChunkedIteratorResult(sqlalchemy.ChunkedIteratorResult):
        ...

    class ClauseElement(sqlalchemy.ClauseElement):
        ...

    class ClauseList(sqlalchemy.ClauseList):
        ...

    class CollectionAggregate(sqlalchemy.CollectionAggregate):
        ...

    class Column(sqlalchemy.Column):
        ...

    class ColumnClause(sqlalchemy.ColumnClause):
        ...

    class ColumnCollection(sqlalchemy.ColumnCollection):
        ...

    class ColumnDefault(sqlalchemy.ColumnDefault):
        ...

    class ColumnElement(sqlalchemy.ColumnElement):
        ...

    class ColumnOperators(sqlalchemy.ColumnOperators):
        ...

    class Compiled(sqlalchemy.Compiled):
        ...

    class CompoundSelect(sqlalchemy.CompoundSelect):
        ...

    class Computed(sqlalchemy.Computed):
        ...

    class Connection(sqlalchemy.Connection):
        ...

    class Constraint(sqlalchemy.Constraint):
        ...

    class CreateEnginePlugin(sqlalchemy.CreateEnginePlugin):
        ...

    class CursorResult(sqlalchemy.CursorResult):
        ...

    class DATE(sqlalchemy.DATE):
        ...

    class DATETIME(sqlalchemy.DATETIME):
        ...

    class DDL(sqlalchemy.DDL):
        ...

    class DDLElement(sqlalchemy.DDLElement):
        ...

    class DECIMAL(sqlalchemy.DECIMAL):
        ...

    class DOUBLE(sqlalchemy.DOUBLE):
        ...

    class Date(sqlalchemy.Date):
        ...

    class DateTime(sqlalchemy.DateTime):
        ...

    class DefaultClause(sqlalchemy.DefaultClause):
        ...

    class Delete(sqlalchemy.Delete):
        ...

    class Dialect(sqlalchemy.Dialect):
        ...

    class Double(sqlalchemy.Double):
        ...

    class Engine(sqlalchemy.Engine):
        ...

    class Enum(sqlalchemy.Enum):
        ...

    class ExceptionContext(sqlalchemy.ExceptionContext):
        ...

    class Executable(sqlalchemy.Executable):
        ...

    class ExecutableDDLElement(sqlalchemy.ExecutableDDLElement):
        ...

    class ExecutionContext(sqlalchemy.ExecutionContext):
        ...

    class Exists(sqlalchemy.Exists):
        ...

    class Extract(sqlalchemy.Extract):
        ...

    class FLOAT(sqlalchemy.FLOAT):
        ...

    class FallbackAsyncAdaptedQueuePool(sqlalchemy.FallbackAsyncAdaptedQueuePool):
        ...

    class FetchedValue(sqlalchemy.FetchedValue):
        ...

    class Float(sqlalchemy.Float):
        ...

    class ForeignKey(sqlalchemy.ForeignKey):
        ...

    class ForeignKeyConstraint(sqlalchemy.ForeignKeyConstraint):
        ...

    class FromClause(sqlalchemy.FromClause):
        ...

    class FromGrouping(sqlalchemy.FromGrouping):
        ...

    class FrozenResult(sqlalchemy.FrozenResult):
        ...

    class Function(sqlalchemy.Function):
        ...

    class FunctionElement(sqlalchemy.FunctionElement):
        ...

    class FunctionFilter(sqlalchemy.FunctionFilter):
        ...

    class GenerativeSelect(sqlalchemy.GenerativeSelect):
        ...

    class Grouping(sqlalchemy.Grouping):
        ...

    class HasCTE(sqlalchemy.HasCTE):
        ...

    class HasPrefixes(sqlalchemy.HasPrefixes):
        ...

    class HasSuffixes(sqlalchemy.HasSuffixes):
        ...

    class INT(sqlalchemy.INT):
        ...

    class INTEGER(sqlalchemy.INTEGER):
        ...

    class Identity(sqlalchemy.Identity):
        ...

    class Index(sqlalchemy.Index):
        ...

    class Insert(sqlalchemy.Insert):
        ...

    class Inspector(sqlalchemy.Inspector):
        ...

    class Integer(sqlalchemy.Integer):
        ...

    class Interval(sqlalchemy.Interval):
        ...

    class IteratorResult(sqlalchemy.IteratorResult):
        ...

    class JSON(sqlalchemy.JSON):
        ...

    class Join(sqlalchemy.Join):
        ...

    class Label(sqlalchemy.Label):
        ...

    class LambdaElement(sqlalchemy.LambdaElement):
        ...

    class LargeBinary(sqlalchemy.LargeBinary):
        ...

    class Lateral(sqlalchemy.Lateral):
        ...

    class MappingResult(sqlalchemy.MappingResult):
        ...

    class MergedResult(sqlalchemy.MergedResult):
        ...

    class MetaData(sqlalchemy.MetaData):
        ...

    class NCHAR(sqlalchemy.NCHAR):
        ...

    class NUMERIC(sqlalchemy.NUMERIC):
        ...

    class NVARCHAR(sqlalchemy.NVARCHAR):
        ...

    class NestedTransaction(sqlalchemy.NestedTransaction):
        ...

    class Null(sqlalchemy.Null):
        ...

    class NullPool(sqlalchemy.NullPool):
        ...

    class Numeric(sqlalchemy.Numeric):
        ...

    class Operators(sqlalchemy.Operators):
        ...

    class Over(sqlalchemy.Over):
        ...

    class PickleType(sqlalchemy.PickleType):
        ...

    class Pool(sqlalchemy.Pool):
        ...

    class PoolProxiedConnection(sqlalchemy.PoolProxiedConnection):
        ...

    class PoolResetState(sqlalchemy.PoolResetState):
        ...

    class PrimaryKeyConstraint(sqlalchemy.PrimaryKeyConstraint):
        ...

    class QueuePool(sqlalchemy.QueuePool):
        ...

    class REAL(sqlalchemy.REAL):
        ...

    class ReleaseSavepointClause(sqlalchemy.ReleaseSavepointClause):
        ...

    class Result(sqlalchemy.Result):
        ...

    class ResultProxy(sqlalchemy.ResultProxy):
        ...

    class ReturnsRows(sqlalchemy.ReturnsRows):
        ...

    class RollbackToSavepointClause(sqlalchemy.RollbackToSavepointClause):
        ...

    class RootTransaction(sqlalchemy.RootTransaction):
        ...

    class Row(sqlalchemy.Row):
        ...

    class RowMapping(sqlalchemy.RowMapping):
        ...

    class SMALLINT(sqlalchemy.SMALLINT):
        ...

    class SQLColumnExpression(sqlalchemy.SQLColumnExpression):
        ...

    class SavepointClause(sqlalchemy.SavepointClause):
        ...

    class ScalarResult(sqlalchemy.ScalarResult):
        ...

    class ScalarSelect(sqlalchemy.ScalarSelect):
        ...

    class Select(sqlalchemy.Select):
        ...

    class SelectBase(sqlalchemy.SelectBase):
        ...

    class SelectLabelStyle(sqlalchemy.SelectLabelStyle):
        ...

    class Selectable(sqlalchemy.Selectable):
        ...

    class Sequence(sqlalchemy.Sequence):
        ...

    class SingleonThreadPool(sqlalchemy.SingleonThreadPool):
        ...

    class SmallInteger(sqlalchemy.SmallInteger):
        ...

    class StatementLambdaElement(sqlalchemy.StatementLambdaElement):
        ...

    class StaticPool(sqlalchemy.StaticPool):
        ...

    class String(sqlalchemy.String):
        ...

    class Subquery(sqlalchemy.Subquery):
        ...

    class TEXT(sqlalchemy.TEXT):
        ...

    class TIME(sqlalchemy.TIME):
        ...

    class TIMESTAMP(sqlalchemy.TIMESTAMP):
        ...

    class Table(sqlalchemy.Table):
        ...

    class TableClause(sqlalchemy.TableClause):
        ...

    class TableSample(sqlalchemy.TableSample):
        ...

    class TableValuedAlias(sqlalchemy.TableValuedAlias):
        ...

    class Text(sqlalchemy.Text):
        ...

    class TextAsFrom(sqlalchemy.TextAsFrom):
        ...

    class TextClause(sqlalchemy.TextClause):
        ...

    class TextualSelect(sqlalchemy.TextualSelect):
        ...

    class Time(sqlalchemy.Time):
        ...

    class Transaction(sqlalchemy.Transaction):
        ...

    class TryCast(sqlalchemy.TryCast):
        ...

    class Tuple(sqlalchemy.Tuple):
        ...

    class TupleType(sqlalchemy.TupleType):
        ...

    class TwoPhaseTransaction(sqlalchemy.TwoPhaseTransaction):
        ...

    class TypeClause(sqlalchemy.TypeClause):
        ...

    class TypeCoerce(sqlalchemy.TypeCoerce):
        ...

    class TypeCompiler(sqlalchemy.TypeCompiler):
        ...

    class TypeDecorator(sqlalchemy.TypeDecorator):
        ...

    class URL(sqlalchemy.URL):
        ...

    class UUID(sqlalchemy.UUID):
        ...

    class UnaryExpression(sqlalchemy.UnaryExpression):
        ...

    class Unicode(sqlalchemy.Unicode):
        ...

    class UnicodeText(sqlalchemy.UnicodeText):
        ...

    class UniqueConstraint(sqlalchemy.UniqueConstraint):
        ...

    class Update(sqlalchemy.Update):
        ...

    class UpdateBase(sqlalchemy.UpdateBase):
        ...

    class Uuid(sqlalchemy.Uuid):
        ...

    class VARBINARY(sqlalchemy.VARBINARY):
        ...

    class VARCHAR(sqlalchemy.VARCHAR):
        ...

    class Values(sqlalchemy.Values):
        ...

    class ValuesBase(sqlalchemy.ValuesBase):
        ...

    class Visitable(sqlalchemy.Visitable):
        ...

    class WithinGroup(sqlalchemy.WithinGroup):
        ...

    class alias(sqlalchemy.alias):
        ...

    class asc(sqlalchemy.asc):
        ...

    class between(sqlalchemy.between):
        ...

    class bindparam(sqlalchemy.bindparam):
        ...

    class case(sqlalchemy.case):
        ...

    class cast(sqlalchemy.cast):
        ...

    class collate(sqlalchemy.collate):
        ...

    class column(sqlalchemy.column):
        ...

    class cte(sqlalchemy.cte):
        ...

    class delete(sqlalchemy.delete):
        ...

    class desc(sqlalchemy.desc):
        ...

    class distinct(sqlalchemy.distinct):
        ...

    class exists(sqlalchemy.exists):
        ...

    class extract(sqlalchemy.extract):
        ...

    class false(sqlalchemy.false):
        ...

    class func(sqlalchemy.func):
        ...

    class funcfilter(sqlalchemy.funcfilter):
        ...

    class insert(sqlalchemy.insert):
        ...

    class inspect(sqlalchemy.inspect):
        ...

    class intersect(sqlalchemy.intersect):
        ...

    class join(sqlalchemy.join):
        ...

    class label(sqlalchemy.label):
        ...

    class lateral(sqlalchemy.lateral):
        ...

    class literal(sqlalchemy.literal):
        ...

    class modifier(sqlalchemy.modifier):
        ...

    class null(sqlalchemy.null):
        ...

    class nullsfirst(sqlalchemy.nullsfirst):
        ...

    class nullslast(sqlalchemy.nullslast):
        ...

    class outerjoin(sqlalchemy.outerjoin):
        ...

    class outparam(sqlalchemy.outparam):
        ...

    class over(sqlalchemy.over):
        ...

    class select(sqlalchemy.select):
        ...

    class table(sqlalchemy.table):
        ...

    class tablesample(sqlalchemy.tablesample):
        ...

    class text(sqlalchemy.text):
        ...

    class true(sqlalchemy.true):
        ...

    class union(sqlalchemy.union):
        ...

    class update(sqlalchemy.update):
        ...

    class values(sqlalchemy.values):
        ...

    ##################################
    ### Sqlalchemy ORM Sub Classes ###
    ##################################
    class AliasOption(sqlalchemy.orm.AliasOption):
        ...

    class AppenderQuery(sqlalchemy.orm.AppenderQuery):
        ...

    class AttributeEventToken(sqlalchemy.orm.AttributeEventToken):
        ...

    class AttributeEvents(sqlalchemy.orm.AttributeEvents):
        ...

    class AttributeState(sqlalchemy.orm.AttributeState):
        ...

    class Bundle(sqlalchemy.orm.Bundle):
        ...

    class CascadeOptions(sqlalchemy.orm.CascadeOptions):
        ...

    class ClassManager(sqlalchemy.orm.ClassManager):
        ...

    class ColumnProperty(sqlalchemy.orm.ColumnProperty):
        ...

    class Composite(sqlalchemy.orm.Composite):
        ...

    class CompositeProperty(sqlalchemy.orm.CompositeProperty):
        ...

    class DeclarativeBase(sqlalchemy.orm.DeclarativeBase):
        ...

    class DeclarativeBaseNoMeta(sqlalchemy.orm.DeclarativeBaseNoMeta):
        ...

    class DeclarativeMeta(sqlalchemy.orm.DeclarativeMeta):
        ...

    class DynamicMapped(sqlalchemy.orm.DynamicMapped):
        ...

    class FromStatement(sqlalchemy.orm.FromStatement):
        ...

    class IdentityMap(sqlalchemy.orm.IdentityMap):
        ...

    class InspectionAttr(sqlalchemy.orm.InspectionAttr):
        ...

    class InspectionAttrExtensionType(sqlalchemy.orm.InspectionAttrExtensionType):
        ...

    class InspectionAttrInfo(sqlalchemy.orm.InspectionAttrInfo):
        ...

    class InstanceEvents(sqlalchemy.orm.InstanceEvents):
        ...

    class InstanceState(sqlalchemy.orm.InstanceState):
        ...

    class InstrumentationEvents(sqlalchemy.orm.InstrumentationEvents):
        ...

    class InstrumentedAttribute(sqlalchemy.orm.InstrumentedAttribute):
        ...

    class KeyFuncDict(sqlalchemy.orm.KeyFuncDict):
        ...

    class Load(sqlalchemy.orm.Load):
        ...

    class LoaderCallableStatus(sqlalchemy.orm.LoaderCallableStatus):
        ...

    class LoaderCriteriaOption(sqlalchemy.orm.LoaderCriteriaOption):
        ...

    class MANYTOMANY(sqlalchemy.orm.MANYTOMANY):
        ...

    class MANYTOONE(sqlalchemy.orm.MANYTOONE):
        ...

    class Mapped(sqlalchemy.orm.Mapped):
        ...

    class MappedAsDataclass(sqlalchemy.orm.MappedAsDataclass):
        ...

    class MappedClassProtocol(sqlalchemy.orm.MappedClassProtocol):
        ...

    class MappedCollection(sqlalchemy.orm.MappedCollection):
        ...

    class MappedColumn(sqlalchemy.orm.MappedColumn):
        ...

    class MappedSQLExpression(sqlalchemy.orm.MappedSQLExpression):
        ...

    class Mapper(sqlalchemy.orm.Mapper):
        ...

    class MapperEvents(sqlalchemy.orm.MapperEvents):
        ...

    class MapperProperty(sqlalchemy.orm.MapperProperty):
        ...

    class NotExtension(sqlalchemy.orm.NotExtension):
        ...

    class ONETOMANY(sqlalchemy.orm.ONETOMANY):
        ...

    class ORMDescriptor(sqlalchemy.orm.ORMDescriptor):
        ...

    class ORMExecuteState(sqlalchemy.orm.ORMExecuteState):
        ...

    class PassiveFlag(sqlalchemy.orm.PassiveFlag):
        ...

    class PropComparator(sqlalchemy.orm.PropComparator):
        ...

    class Query(sqlalchemy.orm.Query):
        ...

    class QueryContext(sqlalchemy.orm.QueryContext):
        ...

    class QueryEvents(sqlalchemy.orm.QueryEvents):
        ...

    class QueryPropertyDescriptor(sqlalchemy.orm.QueryPropertyDescriptor):
        ...

    class QueryableAttribute(sqlalchemy.orm.QueryableAttribute):
        ...

    class Relationship(sqlalchemy.orm.Relationship):
        ...

    class RelationshipDirection(sqlalchemy.orm.RelationshipDirection):
        ...

    class RelationshipProperty(sqlalchemy.orm.RelationshipProperty):
        ...

    class SQLORMExpression(sqlalchemy.orm.SQLORMExpression):
        ...

    class Session(sqlalchemy.orm.Session):
        ...

    class SessionEvents(sqlalchemy.orm.SessionEvents):
        ...

    class SessionTransaction(sqlalchemy.orm.SessionTransaction):
        ...

    class SessionTransactionOrigin(sqlalchemy.orm.SessionTransactionOrigin):
        ...

    class Synonym(sqlalchemy.orm.Synonym):
        ...

    class SynonymProperty(sqlalchemy.orm.SynonymProperty):
        ...

    class UOWTransaction(sqlalchemy.orm.UOWTransaction):
        ...

    class UserDefinedOption(sqlalchemy.orm.UserDefinedOption):
        ...

    class WriteOnlyCollection(sqlalchemy.orm.WriteOnlyCollection):
        ...

    class WriteOnlyMapped(sqlalchemy.orm.WriteOnlyMapped):
        ...

    class aliased(sqlalchemy.orm.aliased):
        ...

    class backref(sqlalchemy.orm.backref):
        ...

    class composite(sqlalchemy.orm.composite):
        ...

    class defaultload(sqlalchemy.orm.defaultload):
        ...

    class defer(sqlalchemy.orm.defer):
        ...

    class deferred(sqlalchemy.orm.deferred):
        ...

    class foreign(sqlalchemy.orm.foreign):
        ...

    class immediateload(sqlalchemy.orm.immediateload):
        ...

    class join(sqlalchemy.orm.join):
        ...

    class joinedload(sqlalchemy.orm.joinedload):
        ...

    class lazyload(sqlalchemy.orm.lazyload):
        ...

    class mapper(sqlalchemy.orm.mapper):
        ...

    class noload(sqlalchemy.orm.noload):
        ...

    class outerjoin(sqlalchemy.orm.outerjoin):
        ...

    class raiseload(sqlalchemy.orm.raiseload):
        ...

    class reconstructor(sqlalchemy.orm.reconstructor):
        ...

    class registry(sqlalchemy.orm.registry):
        ...

    class relationship(sqlalchemy.orm.relationship):
        ...

    class remote(sqlalchemy.orm.remote):
        ...

    class selectinload(sqlalchemy.orm.selectinload):
        ...

    class sessionmaker(sqlalchemy.orm.sessionmaker):
        ...

    class subqueryload(sqlalchemy.orm.subqueryload):
        ...

    class synonym(sqlalchemy.orm.synonym):
        ...

    class undefer(sqlalchemy.orm.undefer):
        ...

    class validates(sqlalchemy.orm.validates):
        ...
